urls: [
  https://dl.ash2txt.org/full-scrolls/Scroll1/PHercParis4.volpkg/,
  https://dl.ash2txt.org/full-scrolls/Scroll2/PHercParis3.volpkg/,
  https://dl.ash2txt.org/full-scrolls/Scroll3/PHerc332.volpkg/,
  https://dl.ash2txt.org/full-scrolls/Scroll4/PHerc1667.volpkg/,
  https://dl.ash2txt.org/full-scrolls/Scroll5/PHerc172.volpkg/
]