scroll1-data: https://dl.ash2txt.org/full-scrolls/Scroll1/PHercParis4.volpkg/
scroll2-data: https://dl.ash2txt.org/full-scrolls/Scroll2/PHercParis3.volpkg/
scroll3-data: https://dl.ash2txt.org/full-scrolls/Scroll3/PHerc332.volpkg/
scroll4-data: https://dl.ash2txt.org/full-scrolls/Scroll4/PHerc1667.volpkg/
scroll5-data: https://dl.ash2txt.org/full-scrolls/Scroll5/PHerc172.volpkg/